CREATE TABLE IF NOT EXISTS task_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    name VARCHAR(255),
    completed BOOLEAN,
    type VARCHAR(50),
    priority VARCHAR(50),
    status VARCHAR(50),
    due_date TIMESTAMP,
    task_list_id BIGINT,
    CONSTRAINT fk_task_task_list FOREIGN KEY (task_list_id) REFERENCES task_list(id)
);